add destroy action

diff --git a/.github/workflows/deploy_monitoring_stack.yaml b/.github/workflows/deploy_monitoring_stack.yaml
--- a/.github/workflows/deploy_monitoring_stack.yaml
+++ b/.github/workflows/deploy_monitoring_stack.yaml
@@ -7,7 +7,12 @@ on:
   pull_request:
     branches:
       - main
-
+  workflow_dispatch:
+    inputs:
+      action:
+        description: 'Terraform Action (apply or destroy)'
+        required: true
+        default: 'apply'
 jobs:
   deploy_monitoring_stack:
     runs-on: ubuntu-latest
@@ -39,8 +44,16 @@ jobs:
 
     - name: Terraform Init and Apply
       run: |
-        terraform init
-        terraform apply -auto-approve
+        if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+            terraform init
+            terraform apply -auto-approve
+        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+            terraform init
+            terraform destroy -auto-approve
+        else
+            echo "Invalid action specified"
+            exit 1
+        fi
       working-directory: ./Terraform
 
     - name: Generate SSH Key File
